### ISSUE TITLE
pyBOAT

### ISSUE THREAD

**Issue by tensionhead** [MaxStrange/pyboat#1]
Dear Max,

I am developing a time-frequency analysis tool for basic biological research. After long considerations we finally came up with a nice sounding acronym: BOAT (Biological Oscillations Analysis Tool) Now as it's written in Python, I was suggesting to name our tool pyBOAT, then I realized that you came up with such great name first. I wanted to ask you, if you think it's ok that we both use this name, as your project and mine are in totally different domains. 
The working title of my project so far is TFApy, you can check it out on my github if you want! Thanks for your considerations.

Best,
Gregor

PS: The actual development is done here https://git.embl.de/moenke/TFApy/-/tree/paper , on github there is only the mirrored master branch. I plan to merge soon, and then publish the whole story..

**Comment by MaxStrange** [comment]
Hi @tensionhead , I don't mind at all if you use the name PyBOAT. This project is named the same because of "gun-boat diplomacy" and this was meant to be a diplomacy-playing bot (Diplomacy is a board game, and there is a variant called gunboat).

Anyway, this project has always been something I've wanted to come back to, but certainly won't any time soon, and besides, even if I do, it won't likely be pip-installable, so please, by all means take the name!

**Comment by tensionhead** [comment]
Hi @MaxStrange ,

thank you so much, that reduces the amount of headaches substantially! Also only now learned about the game diplomacy :]

All the best and thanks again,
tensionhead (aka Gregor)
